PUT http://localhost:3003/api/resetpassword
Content-Type: application/json

{
  "newPassword" : "password2",
  "resetLink" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMTY0OTNjNmM3NmYyOTViMjIzM2E2ZiIsImlhdCI6MTY0NTYzMDczNSwiZXhwIjoxNjQ1NjM0MzM1fQ.OjgYvNHNqPgghvDorU-KpfeJgyA64UKfGo0DbA_Ytdc"
}